# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Compliancekit < Formula
  desc "Open-source compliance scanner for cloud and Linux infrastructure -- SOC 2, ISO 27001, CIS"
  homepage "https://github.com/darpanzope/compliancekit"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/darpanzope/compliancekit/releases/download/v0.5.0/compliancekit_0.5.0_darwin_amd64.tar.gz"
      sha256 "88bc88ea19e1857e27e77545a0dfede4c7b7a9b9ea5a75aed1d62f050685e8a0"

      define_method(:install) do
        bin.install "compliancekit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/darpanzope/compliancekit/releases/download/v0.5.0/compliancekit_0.5.0_darwin_arm64.tar.gz"
      sha256 "c78622e0787e83250e392d13b89648ddde2e5ff50edb6232b153531d7004524d"

      define_method(:install) do
        bin.install "compliancekit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/darpanzope/compliancekit/releases/download/v0.5.0/compliancekit_0.5.0_linux_amd64.tar.gz"
      sha256 "c1ba9a1cd28b75050f0eb3a99b50754b27a4eff774b36c279f64f06f980c3d2d"
      define_method(:install) do
        bin.install "compliancekit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/darpanzope/compliancekit/releases/download/v0.5.0/compliancekit_0.5.0_linux_arm64.tar.gz"
      sha256 "e2322c0037bcc889719e1f224da714f9257df1cfe48ea46acf2f0dc4c67ab1db"
      define_method(:install) do
        bin.install "compliancekit"
      end
    end
  end

  test do
    system "#{bin}/compliancekit version"
  end
end
