# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Compliancekit < Formula
  desc "Open-source compliance scanner for cloud and Linux infrastructure -- SOC 2, ISO 27001, CIS"
  homepage "https://github.com/darpanzope/compliancekit"
  version "0.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/darpanzope/compliancekit/releases/download/v0.6.0/compliancekit_0.6.0_darwin_amd64.tar.gz"
      sha256 "f3ba724e960bf3e022b3e3af3af62209f696163216b699cdabf485a438ec69e5"

      define_method(:install) do
        bin.install "compliancekit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/darpanzope/compliancekit/releases/download/v0.6.0/compliancekit_0.6.0_darwin_arm64.tar.gz"
      sha256 "dab146261cc87869c6b4e808ee1075bfba0b199da09b6f8a5b9442691da59515"

      define_method(:install) do
        bin.install "compliancekit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/darpanzope/compliancekit/releases/download/v0.6.0/compliancekit_0.6.0_linux_amd64.tar.gz"
      sha256 "baf88da7bca20988463afd73d1c4cd06054c0b770fd07b2f685a64decd072ba6"
      define_method(:install) do
        bin.install "compliancekit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/darpanzope/compliancekit/releases/download/v0.6.0/compliancekit_0.6.0_linux_arm64.tar.gz"
      sha256 "8e540df39106f3f3791cf3f4a3e06e4d03c0b43137b8478bb236f87560c2c210"
      define_method(:install) do
        bin.install "compliancekit"
      end
    end
  end

  test do
    system "#{bin}/compliancekit version"
  end
end
