# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Compliancekit < Formula
  desc "Open-source compliance scanner for cloud and Linux infrastructure -- SOC 2, ISO 27001, CIS"
  homepage "https://github.com/darpanzope/compliancekit"
  version "0.7.0-rc1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/darpanzope/compliancekit/releases/download/v0.7.0-rc1/compliancekit_0.7.0-rc1_darwin_amd64.tar.gz"
      sha256 "4be3fca8295033fee1f5fde188a1aef4170532f64b22c94a6b229c870d53cad7"

      define_method(:install) do
        bin.install "compliancekit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/darpanzope/compliancekit/releases/download/v0.7.0-rc1/compliancekit_0.7.0-rc1_darwin_arm64.tar.gz"
      sha256 "8f450c3afcfe5acb782c5a4ce7d2a726237c0df94f0a98cedfa6086dcc4fbe15"

      define_method(:install) do
        bin.install "compliancekit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/darpanzope/compliancekit/releases/download/v0.7.0-rc1/compliancekit_0.7.0-rc1_linux_amd64.tar.gz"
      sha256 "c1edab49fdca2525181d9f67b0e2317c890945fc1458f6bdb11a604a592e570d"
      define_method(:install) do
        bin.install "compliancekit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/darpanzope/compliancekit/releases/download/v0.7.0-rc1/compliancekit_0.7.0-rc1_linux_arm64.tar.gz"
      sha256 "99f4ffb566ec1596619fc8309079c2947a271e6563c5a92228cbb9dcd354791b"
      define_method(:install) do
        bin.install "compliancekit"
      end
    end
  end

  test do
    system "#{bin}/compliancekit version"
  end
end
